"""Add models

Revision ID: 3965b3afad2f
Revises: 
Create Date: 2026-07-15 11:21:58.793838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3965b3afad2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('new', 'under_review', 'confirmed_suspicious', 'false_positive', 'closed', name='alertstatus'), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_domain_id'), 'alerts', ['domain_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('domain_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('rdap_registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rdap_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rdap_registrar', sa.String(), nullable=True),
    sa.Column('rdap_domain_age_days', sa.Integer(), nullable=True),
    sa.Column('dns_a_record_count', sa.Integer(), nullable=True),
    sa.Column('dns_mx_record_present', sa.Boolean(), nullable=True),
    sa.Column('dns_ns_record_count', sa.Integer(), nullable=True),
    sa.Column('cert_issuer', sa.String(), nullable=True),
    sa.Column('cert_validity_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_enrichments_domain_id'), 'domain_enrichments', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domain_enrichments_id'), 'domain_enrichments', ['id'], unique=False)
    op.add_column('domains', sa.Column('registered_domain', sa.String(), nullable=True))
    op.alter_column('domains', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('received', 'normalised', 'initially_scored', 'enrichment_pending', 'enriching', 'fully_scored', 'enrichment_failed', 'reviewed', 'closed', name='processingstate'),
               existing_nullable=True)
    op.create_index(op.f('ix_domains_registered_domain'), 'domains', ['registered_domain'], unique=False)
    op.create_foreign_key(None, 'features', 'domains', ['domain_id'], ['id'])
    op.add_column('scores', sa.Column('fast_lexical_score', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('final_risk_score', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'scores', 'domains', ['domain_id'], ['id'])
    op.drop_column('scores', 'risk_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_column('scores', 'final_risk_score')
    op.drop_column('scores', 'fast_lexical_score')
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_index(op.f('ix_domains_registered_domain'), table_name='domains')
    op.alter_column('domains', 'status',
               existing_type=sa.Enum('received', 'normalised', 'initially_scored', 'enrichment_pending', 'enriching', 'fully_scored', 'enrichment_failed', 'reviewed', 'closed', name='processingstate'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('domains', 'registered_domain')
    op.drop_index(op.f('ix_domain_enrichments_id'), table_name='domain_enrichments')
    op.drop_index(op.f('ix_domain_enrichments_domain_id'), table_name='domain_enrichments')
    op.drop_table('domain_enrichments')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_domain_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
